#!/bin/bash
clear
echo -e "\E[44;1;37m     INSTALACAO BOT DO MRSILENT1     \E[0m"
echo -e "\nINSTALANDO AGUARDE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget https://drive.google.com/uc?id=15LvQ_kQ5_xY0cCrOPNSBwTTFPj9i627M&export=download
unzip botteste.zip > /dev/null 2>&1 && rm botteste.zip > /dev/null 2>&1
chmod +x $(ls)
mv botteste /bin/botteste
clear && echo -e "INSTALADO COM SUCESSO !\nPARA ATIVAR EXECULTE O COMANDO botteste"
cd $HOME && rm inst-botteste > /dev/null 2>&1
